export const mainUrl = 'https://palase.roitiv.com/projektet';
// export const BASE_URL = 'http://localhost:8080';
export const BASE_URL = 'https://srv412786.hstgr.cloud:7151'
export const objectImageUrl = 'images/'
export const planmetricImageUrl = '/images/planimetrit/'
// export const BASE_URL = 'http://localhost:8845';
// export const BASE_URL_JEHONA = 'http://localhost:8845';
export const STORE_IMAGE_PATH = 'objektetImg/';
export const EURO_SYMBOL = '€';
export const homepage = `https://palase.roitiv.com/projektet`
export const galleryDir = 'assets/gallery/'
export const imagePath = `https://palase.roitiv.com/projektet/objektetImg/`
export const pdfPath = `https://palase.roitiv.com/projektet/pdf/`
export const vTourPath = `/360/interior`
export const orientationImgPath = `images/orientation/`